name: Veristat fail test
on:
  pull_request:
    paths:
      - 'action.yaml'
      - '.github/workflows/test.yaml'
  push:
    paths:
      - 'action.yaml'
      - '.github/workflows/test.yaml'

jobs:
  fail-simple:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Run veristat
      continue-on-error: true
      uses: ./

  fail-compare:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Run veristat
      continue-on-error: true
      uses: ./
      with:
        compare: true